version: "3"
services:
    principal:
        build: ./app/frontend
        image: application
        container_name: appweb
        restart: always
        ports:
            - 80:80
            - 443:443
    eReports:
        build: ./oracle-client
        image: oracle-client
        container_name: eReports
        volumes:
            - ./eReports:/eReports
        depends_on:
            - database-oracle
            - mongodb
        networks:
            - myapp
        ports:
            - 9000:9000
        command: bash -c "sleep 90; cd /eReports && npm i && npm install -g nodemon && npm start"
        restart: always
        
    database-oracle:
        build: ./db-oracle
        image: database-oracle
        container_name: db-oracle
        restart: always
        ports:
            - "49160:22"
            - 49161:1521
            - 8080:8080
        environment:
            - ORACLE_ENABLE_XDB=true
            - ORACLE_ALLOW_REMOTE=true

    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - TZ=America/Sao_Paulo
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        networks:
            - myapp
        command: sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && mongod --smallfiles --logpath=/dev/null"
        restart: always
networks:
    myapp:
        driver: bridge
  